import { RGBAColor } from "./types.js";
export declare const Colors: {
    BLACK: RGBAColor;
    WHITE: RGBAColor;
    RED: RGBAColor;
    GREEN: RGBAColor;
    BLUE: RGBAColor;
    YELLOW: RGBAColor;
    MAGENTA: RGBAColor;
    CYAN: RGBAColor;
    DARK_BLUE: RGBAColor;
    LIGHT_BLUE: RGBAColor;
    PURPLE: RGBAColor;
    PINK: RGBAColor;
    GRAY: RGBAColor;
    GREY: RGBAColor;
    ORANGE: RGBAColor;
    AQUAMARINE: RGBAColor;
    TRANSPARENT: RGBAColor;
    from8bit(color256: number): RGBAColor;
    from16bit(color: number): RGBAColor;
    from24bit(color: number): RGBAColor;
    from32bit(color: number): RGBAColor;
};
