import { RGBAColor } from "./types.js";
export declare class Colors {
    static get BLACK(): RGBAColor;
    static get WHITE(): RGBAColor;
    static get RED(): RGBAColor;
    static get GREEN(): RGBAColor;
    static get BLUE(): RGBAColor;
    static get YELLOW(): RGBAColor;
    static get MAGENTA(): RGBAColor;
    static get CYAN(): RGBAColor;
    static get DARK_BLUE(): RGBAColor;
    static get NAVY(): RGBAColor;
    static get LIGHT_BLUE(): RGBAColor;
    static get TEAL(): RGBAColor;
    static get DARK_CYAN(): RGBAColor;
    static get PURPLE(): RGBAColor;
    static get PINK(): RGBAColor;
    static get GRAY(): RGBAColor;
    static get GREY(): RGBAColor;
    static get ORANGE(): RGBAColor;
    static get AQUAMARINE(): RGBAColor;
    static get OLIVE(): RGBAColor;
    static get DARK_RED(): RGBAColor;
    static get SALMON(): RGBAColor;
    static get TOMATO(): RGBAColor;
    static get GOLD(): RGBAColor;
    static get DARK_GREEN(): RGBAColor;
    static get INDIGO(): RGBAColor;
    static get TRANSPARENT(): RGBAColor;
    static from8bit(color256: number): RGBAColor;
    static from16bit(color: number): RGBAColor;
    static from24bit(color: number): RGBAColor;
    static from32bit(color: number): RGBAColor;
}
