import { Key } from './types.js';
declare let sdl2bind: any;
export { sdl2bind };
export declare function getTicks(): any;
export declare function setRenderingSequence(): Promise<void>;
export declare function clearRenderingSequence(): Promise<void>;
export declare function getWindow(title: string, xPos: number, yPos: number, width: number, height: number, flags: number): ArrayBuffer;
export declare function getRenderer(window: ArrayBuffer, index: number, flag: number): any;
export declare function showWindow(window: ArrayBuffer): Promise<void>;
export declare function hideWindow(window: ArrayBuffer): Promise<void>;
export declare function clearWithColor(renderer: ArrayBuffer, r: number, g: number, b: number, alpha: number): Promise<void>;
export declare function delay(ms: number): Promise<void>;
export declare function setPoint(renderer: ArrayBuffer, r: number, g: number, b: number, a: number, px: number, py: number): Promise<void>;
export declare function setLine(renderer: ArrayBuffer, r: number, g: number, b: number, a: number, px1: number, py1: number, px2: number, py2: number): Promise<void>;
export declare function setAntialias(): Promise<void>;
export declare function setImage(renderer: ArrayBuffer, filename: string, imgInitFlag: number): Promise<void>;
export declare function setPNG(renderer: ArrayBuffer, filename: string): Promise<void>;
export declare function setJPG(renderer: ArrayBuffer, filename: string): Promise<void>;
export declare function setRectangle(renderer: ArrayBuffer, x: number, y: number, width: number, height: number, r: number, g: number, b: number, a: number, fill: boolean): Promise<void>;
export declare function renderPresent(renderer: ArrayBuffer): Promise<void>;
export declare function setRawData(renderer: ArrayBuffer, buffer: Uint8Array, bitPerPixel: number, width: number, height: number): Promise<void>;
export declare function watchRawData(renderer: ArrayBuffer, width: number, height: number): Uint8Array;
export declare function savePNG(renderer: ArrayBuffer, width: number, height: number, filename: string): Promise<void>;
export declare function saveJPG(renderer: ArrayBuffer, width: number, height: number, filename: string): Promise<void>;
export declare function setRenderScale(renderer: ArrayBuffer, width: number, height: number, scale: number): Promise<void>;
export declare function onClickEvent(callback: (x: number, y: number) => void): Promise<void>;
export declare function onKeyDownEvent(callback: (key: Key) => void): Promise<void>;
export declare function onKeyUpEvent(callback: (key: Key) => void): Promise<void>;
export declare function onKeysDownEvent(callback: (key: Key[]) => void): Promise<void>;
export declare function onKeysUpEvent(callback: (key: Key[]) => void): Promise<void>;
export declare function refresh(renderer: ArrayBuffer): Promise<void>;
export declare function setText(renderer: ArrayBuffer, text: string, r: number, g: number, b: number, x: number, y: number): Promise<void>;
export declare function setArc(renderer: ArrayBuffer, x: number, y: number, radius: number, angle1: number, angle2: number, r: number, g: number, b: number, a: number): Promise<void>;
export declare function setTexture(renderer: ArrayBuffer, x: number, y: number, textureFile: string): Promise<void>;
