export declare const SDL_Init_Flags: {
    SDL_INIT_TIMER: number;
    SDL_INIT_AUDIO: number;
    SDL_INIT_VIDEO: number;
    SDL_INIT_JOYSTICK: number;
    SDL_INIT_HAPTIC: number;
    SDL_INIT_GAMECONTROLLER: number;
    SDL_INIT_EVENTS: number;
    SDL_INIT_SENSOR: number;
    SDL_INIT_NOPARACHUTE: number;
};
export declare const SDL_Init_Everything: number;
export declare const SDL_WindowPos: {
    SDL_WINDOWPOS_CENTERED: number;
    SDL_WINDOWPOS_UNDEFINED: number;
};
export declare const SDL_Window_Flags: {
    SDL_WINDOW_FULLSCREEN: number;
    SDL_WINDOW_OPENGL: number;
    SDL_WINDOW_SHOWN: number;
    SDL_WINDOW_HIDDEN: number;
    SDL_WINDOW_BORDERLESS: number;
    SDL_WINDOW_RESIZABLE: number;
    SDL_WINDOW_MINIMIZED: number;
    SDL_WINDOW_MAXIMIZED: number;
    SDL_WINDOW_MOUSE_GRABBED: number;
    SDL_WINDOW_INPUT_FOCUS: number;
    SDL_WINDOW_MOUSE_FOCUS: number;
    SDL_WINDOW_FOREIGN: number;
    SDL_WINDOW_ALLOW_HIGHDPI: number;
    SDL_WINDOW_MOUSE_CAPTURE: number;
    SDL_WINDOW_ALWAYS_ON_TOP: number;
    SDL_WINDOW_SKIP_TASKBAR: number;
    SDL_WINDOW_UTILITY: number;
    SDL_WINDOW_TOOLTIP: number;
    SDL_WINDOW_POPUP_MENU: number;
    SDL_WINDOW_KEYBOARD_GRABBED: number;
    SDL_WINDOW_VULKAN: number;
    SDL_WINDOW_METAL: number;
};
export declare const IMG_Init_Flags: {
    IMG_INIT_JPG: number;
    IMG_INIT_PNG: number;
    IMG_INIT_TIF: number;
    IMG_INIT_WEBP: number;
    IMG_INIT_JXL: number;
    IMG_INIT_AVIF: number;
};
export declare const SDL_PIXEL_FORMAT: {
    SDL_PIXELFORMAT_UNKNOWN: number;
    SDL_PIXELFORMAT_RGB444: number;
    SDL_PIXELFORMAT_BGR444: number;
    SDL_PIXELFORMAT_RGB555: number;
    SDL_PIXELFORMAT_BGR555: number;
    SDL_PIXELFORMAT_RGBA4444: number;
    SDL_PIXELFORMAT_ARGB4444: number;
    SDL_PIXELFORMAT_RGBA1555: number;
    SDL_PIXELFORMAT_ARGB5551: number;
    SDL_PIXELFORMAT_RGB565: number;
    SDL_PIXELFORMAT_BGR565: number;
    SDL_PIXELFORMAT_RGB888: number;
    SDL_PIXELFORMAT_RGBA8888: number;
    SDL_PIXELFORMAT_RGB332: number;
};
export declare const SDL_TEXTURE_ACCESS: {
    SDL_TEXTUREACCESS_STATIC: number;
    SDL_TEXTUREACCESS_STREAMING: number;
    SDL_TEXTUREACCESS_TARGET: number;
};
export declare const NULL: ArrayBuffer;
